"""add details to voices

Revision ID: 3cc4cefa49b4
Revises: ca3551695d68
Create Date: 2026-01-15 10:17:51.464579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc4cefa49b4'
down_revision: Union[str, Sequence[str], None] = 'ca3551695d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('voices', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'description')
    op.drop_column('voices', 'gender')
    # ### end Alembic commands ###
