"""add default voice to user

Revision ID: 7936759c4ac5
Revises: 58f0b253ae63
Create Date: 2026-01-15 11:29:12.421764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7936759c4ac5'
down_revision: Union[str, Sequence[str], None] = '58f0b253ae63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_voice_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'voices', ['default_voice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_voice_id')
    # ### end Alembic commands ###
